### ISSUE TITLE
[Task] account 검색 결과 페이지

### ISSUE THREAD

**Issue by devCoderian** [codestates/BTAFinalProject-06#20]
### ISSUE
- Group: client, server
- Type: feature
- Detail: fix actions from client redux

### TODO
1. [ ] Stacks 계정 생성
2. [ ] accounts 조회 페이지 생성
3. [ ] 해당 account balance, 최근 tx nonce 가져오기
4. [ ] 해당 account의 거래내역 가져오기
