### ISSUE TITLE
[Task] 노드 탐구 2

### ISSUE THREAD

**Issue by chochohert** [codestates/BTAFinalProject-06#25]
### ISSUE
- Group:  server
- Type: feature
- Detail: 노드 탐구 2

### TODO
1. [x] 노드 동기화 확인
2. [ ] 마이크로 블록 확인
3. [ ] 로컬 노드 두개 띄우기

### Estimated time
```3h```

![image](https://user-images.githubusercontent.com/17466930/200118224-84d9e3a1-768b-43ce-a8c9-240dbf3b315e.png)
이 과정이 끝나야 동기화 가능,, 시간이 좀 걸린다.

![image](https://user-images.githubusercontent.com/17466930/200118304-ce8da690-02a8-45af-81d7-3d93bf41f607.png)

![image](https://user-images.githubusercontent.com/17466930/200118334-4b26db86-a65b-4897-a3dd-afa23fb2a5df.png)

![image](https://user-images.githubusercontent.com/17466930/200118351-1fbfcee6-afe8-4737-b6d9-59701a2982db.png)

![image](https://user-images.githubusercontent.com/17466930/200118415-764e7e60-3121-45eb-8dd3-7efb511076e5.png)
