### ISSUE TITLE
[Task] Main page stacks info 가져오기

### ISSUE THREAD

**Issue by devCoderian** [codestates/BTAFinalProject-06#28]
### ISSUE
- Group: client
- Type: feature
- Detail:  Main page stacks info 가져오기

### TODO
1. [ ] stacks 시세 표기
2. [ ] 최근 생성 block 가져오기
3. [ ] 최근 거래 내역 가져오기
