### ISSUE TITLE
[Task]  도커 nodejs 설정

### ISSUE THREAD

**Issue by chochohert** [codestates/BTAFinalProject-06#30]
### ISSUE
- Group: server
- Type: feature
- Detail: 도커 nodejs 설정

### TODO
1. [ ] 데몬용 도커 nodejs 서버 설정
2. [ ] nodejs 서버와 mysql 연동
3. [ ] stacks 노드와 쿼리 확인

### Estimated time
```3h```
