### ISSUE TITLE
[Task] 밸런스 체크

### ISSUE THREAD

**Issue by chochohert** [codestates/BTAFinalProject-06#4]
### ISSUE
- Group: client
- Type: feature
- Detail: 계정 밸런스 체크

### TODO
1. [x] 메인 화면 페이지 설정
2. [x] 계정 밸런스를 가져온다.
3. [x] 트랜잭션 정보 등?을 설정한다.

### Estimated time
```3h```
