### ISSUE TITLE
[Task] 월렛 변경 2

### ISSUE THREAD

**Issue by chochohert** [codestates/BTAFinalProject-06#49]
### ISSUE
- Group: client
- Type: refactor
- Detail: 월렛 변경 2

### TODO
1. [ ] 전송 처리 수정
2. [ ] 트랜잭션 리스트 가져오기
3. [ ] 세팅 쪽 UI 잡기

### Estimated time
```2.5h```
